services:

  patient-service:
    build: ./patient-service
    ports:
      - "4000:4000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    depends_on:
      - patient-service-db

    networks:
      - internal

  patient-service-db:
    image: postgres:latest
    ports:
      - "5001:5432"
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - internal
    volumes:
      - patient-service-db-data:/var/lib/postgresql

networks:
  internal:
    driver: bridge

volumes:
  patient-service-db-data:


